name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Analysing the code with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
     
      - name: Create Bundle Code
        run: |
          zip -r bundle.zip .

      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: python-bundle
          path: bundle.zip

  publish:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:

      - name: Download Bundle Artifact
        uses: actions/download-artifact@v4
        with:
          name: python-bundle
          path: temp-artifact
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1
        outputs:
          upload_url: ${{ steps.step_create_release.outputs.upload_url }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
          asset_path: ./temp-artifact/bundle.zip
          asset_name: bundle.zip
          asset_content_type: application/zip

