name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assurez-vous d'avoir un fichier requirements.txt
    
    - name: Build Bundle
      run: zip -r code-bundle.zip .

    - name: Upload Bundle
      uses: actions/upload-artifact@v2
      with:
        name: code-bundle
        path: code-bundle.zip